### ISSUE TITLE
cameraId was null

### ISSUE THREAD

**Issue by complexi** [EzequielAdrianM/Camera2Vision#1]
samsung s3 express

03-17 00:25:00.378 27764-27764/com.example.ezequiel.camera2 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.example.ezequiel.camera2, PID: 27764
                                                                              java.lang.IllegalArgumentException: cameraId was null
                                                                                  at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:445)
                                                                                  at com.example.ezequiel.camera2.others.Camera2Source.openCamera(Camera2Source.java:667)
                                                                                  at com.example.ezequiel.camera2.others.Camera2Source.start(Camera2Source.java:530)
                                                                                  at com.example.ezequiel.camera2.others.CameraSourcePreview.startIfReady(CameraSourcePreview.java:126)
                                                                                  at com.example.ezequiel.camera2.others.CameraSourcePreview.access$200(CameraSourcePreview.java:21)
                                                                                  at com.example.ezequiel.camera2.others.CameraSourcePreview$2.onSurfaceTextureAvailable(CameraSourcePreview.java:166)

**Comment by EzequielAdrianM** [comment]
Can you please tell me which Android version were you using?

**Comment by complexi** [comment]
6.0.1

**Comment by EzequielAdrianM** [comment]
Samsung Galaxy Express comes with Android 4.1 (API Level 16) by default. The hardware does not support Camera2, it's up to the CyanogenMod team to find out drivers.

**Comment by EzequielAdrianM** [comment]
This was an issue and I have fixed it. Please check out the new version :)
